# fly.toml app configuration file generated for postgres-sequelize-backend on 2025-02-23T12:06:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'postgres-sequelize-backend'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
